//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIAutomation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIAutomation.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get window in {0} milliseconds by: process name: &apos;{1}&apos;, process Id: {2}, window title: &apos;{3}&apos;, automationId: &apos;{4}&apos;, className: &apos;{5}&apos;..
        /// </summary>
        internal static string GetWindowCommand_Error_Timeout {
            get {
                return ResourceManager.GetString("GetWindowCommand_Error_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error in &apos;{0}&apos; ProcessRecord.
        /// </summary>
        internal static string GetWindowCommand_Error_Unknown_error {
            get {
                return ResourceManager.GetString("GetWindowCommand_Error_Unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither ProcessName nor window Name are provided. Or ProcessId == 0.
        /// </summary>
        internal static string GetWindowCommand_Error_wrong_input {
            get {
                return ResourceManager.GetString("GetWindowCommand_Error_wrong_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no processName, name, processid or process was supplied.
        /// </summary>
        internal static string GetWindowCommand_Verbose_no_processName__name__processid_or_process_was_supplied {
            get {
                return ResourceManager.GetString("GetWindowCommand_Verbose_no_processName__name__processid_or_process_was_supplied", resourceCulture);
            }
        }
    }
}
