/*
 * Created by SharpDevelop.
 * User: Alexander Petrovskiy
 * Date: 10/31/2014
 * Time: 6:21 PM
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */

namespace Tmx.Core
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Tmx.Interfaces;
    using Tmx.Interfaces.TestStructure;
    
    /// <summary>
    /// Description of TestResultsImporter.
    /// </summary>
    public class TestResultsImporter
    {
        public List<ITestSuite> ImportTestResultsFromXdocument(XDocument doc)
        {
            var df = doc.Root.Name.Namespace;
            var suites = from suite in doc.Descendants("suite")
                                  where suite.Attribute("name").Value != TestData.Autogenerated
                                  select suite;
            return ImportTestSuites(suites);
        }
        
		public List<ITestSuite> ImportTestSuites(IEnumerable<XElement> suites)
		{
            string lastTestSuiteName = string.Empty;
            var importedTestSuites = new List<ITestSuite>();
            
			foreach (var singleSuite in suites) {
				lastTestSuiteName = singleSuite.Attribute("name").Value;
				string suiteDescription = string.Empty;
				try {
					suiteDescription = singleSuite.Attribute("description").Value;
				} catch {
				}
				// var testSuite = TestData.GetTestSuite(singleSuite.Attribute("name").Value, singleSuite.Attribute("id").Value, singleSuite.Attribute("platformId").Value);
				var testSuite = importedTestSuites
				    .FirstOrDefault(ts => ts.Id == singleSuite.Attribute("id").Value &&
                                ts.Name == singleSuite.Attribute("name").Value &&
                                ts.PlatformId == singleSuite.Attribute("platformId").Value);
                // TestData.CurrentTestSuite = testSuite;
                if (null == testSuite)
					// TestData.AddTestSuite(singleSuite.Attribute("name").Value, singleSuite.Attribute("id").Value, singleSuite.Attribute("platformId").Value, suiteDescription, null, null);
                    testSuite = new TestSuite {
                        Id = singleSuite.Attribute("id").Value,
                        Name = singleSuite.Attribute("name").Value,
                        PlatformId = singleSuite.Attribute("platformId").Value,
                        Description = suiteDescription,
                        TimeSpent = Convert.ToDouble(singleSuite.Attribute("timeSpent").Value)
                    };
                var scenarios = from scenario in singleSuite.Descendants("scenario")
                                            where scenario.Attribute("name").Value != TestData.Autogenerated
                                            select scenario;
                testSuite.TestScenarios.AddRange(importTestScenarios(scenarios));
                importedTestSuites.Add(testSuite);
				// TODO: refresh imported suites
				// TestData.RefreshSuiteStatistics(TestData.CurrentTestSuite, true);
			}
            return importedTestSuites;
		}

		List<ITestScenario> importTestScenarios(IEnumerable<XElement> scenarios)
		{
            string lastTestScenarioName = string.Empty;
            var importedTestScenarios = new List<ITestScenario>();
            
			foreach (var singleScenario in scenarios) {
				lastTestScenarioName = singleScenario.Attribute("name").Value;
				string scenarioDescription = string.Empty;
				try {
					scenarioDescription = singleScenario.Attribute("description").Value;
				} catch {
				}
				// var testScenario = TestData.GetTestScenario(TestData.CurrentTestSuite, singleScenario.Attribute("name").Value, singleScenario.Attribute("id").Value, TestData.CurrentTestSuite.Name, TestData.CurrentTestSuite.Id, TestData.CurrentTestSuite.PlatformId);
				var testScenario = importedTestScenarios
				    .FirstOrDefault(tsc => tsc.Name == singleScenario.Attribute("name").Value &&
				           tsc.Id == singleScenario.Attribute("id").Value &&
				           tsc.PlatformId == singleScenario.Attribute("platformId").Value);
				// TestData.CurrentTestScenario = testScenario;
                if (null == testScenario)
                    // TestData.AddTestScenario(TestData.CurrentTestSuite, singleScenario.Attribute("name").Value, singleScenario.Attribute("id").Value, scenarioDescription, string.Empty, string.Empty, singleScenario.Attribute("platformId").Value, null, null);
                    testScenario = new TestScenario {
                        Id = singleScenario.Attribute("id").Value,
                        Name = singleScenario.Attribute("name").Value,
                        PlatformId = singleScenario.Attribute("platformId").Value,
                        Description = scenarioDescription,
                        TimeSpent = Convert.ToDouble(singleScenario.Attribute("timeSpent").Value)
                };
                var testResults = from testResult in singleScenario.Descendants("testResult")
                                  //where testResult.Attribute("name").Value != "autoclosed"
				select testResult;
                testScenario.TestResults.AddRange(importTestResults(testResults));
                importedTestScenarios.Add(testScenario);
			}
            return importedTestScenarios;
		}

		List<ITestResult> importTestResults(IEnumerable<XElement> testResults)
		{
            string lastTestResultName = string.Empty;
            var importedTestResults = new List<ITestResult>();
            
			foreach (var singleTestResult in testResults) {
				lastTestResultName = singleTestResult.Attribute("name").Value;
				bool passedValue = false;
				bool knownIssueValue = false;
				try {
                    passedValue |= "PASSED" == singleTestResult.Attribute("status").Value;
                    knownIssueValue |= "KNOWN ISSUE" == singleTestResult.Attribute("status").Value;
				} catch {
				}
				TestResultOrigins origin = TestResultOrigins.Logical;
				try {
                    if ("TECHNICAL" == singleTestResult.Attribute("origin").Value.ToUpper())
                        origin = TestResultOrigins.Technical;
                    if ("AUTOMATIC" == singleTestResult.Attribute("origin").Value.ToUpper())
                        origin = TestResultOrigins.Automatic;
				} catch {
				}
				if ((TestResultOrigins.Technical == origin) &&
				    passedValue) {
					continue;
				}
				string testResultDescription = string.Empty;
				try {
					testResultDescription = singleTestResult.Attribute("description").Value;
				} catch {
				}
				
				// TestData.AddTestResult(singleTestResult.Attribute("name").Value, singleTestResult.Attribute("id").Value, passedValue, knownIssueValue, false, null, null, testResultDescription, origin, true);
				// var currentlyAddedTestResult = TestData.CurrentTestScenario.TestResults[TestData.CurrentTestScenario.TestResults.Count - 1];
				var testResult = new TestResult {
				    Id = singleTestResult.Attribute("id").Value,
				    Name = singleTestResult.Attribute("name").Value,
				    Description = testResultDescription,
				    enStatus = (!passedValue ? TestResultStatuses.Failed : knownIssueValue ? TestResultStatuses.KnownIssue : passedValue ? TestResultStatuses.Passed : TestResultStatuses.NotTested) // ,
                    // Timestamp = singleTestResult.Attribute("timestamp").Value
				};
				testResult.SetOrigin(origin);
				testResult.SetTimeSpent(Convert.ToDouble(singleTestResult.Attribute("timeSpent").Value));
				try {
					testResult.PlatformId = singleTestResult.Attribute("platformId").Value;
				} catch (Exception) {
					//                                cmdlet.WriteVerbose(cmdlet, "adding test platform to the current test result");
					//                                cmdlet.WriteVerbose(cmdlet, eTestResultPlatform.Message);
				}
				try {
					// lastTestResultDetailName = string.Empty;
                    var testResultDetails = from testResultDetail in singleTestResult.Descendants("detail")
                                            select testResultDetail;
					if (null == testResultDetails || !testResultDetails.Any())
						continue;
					importTestResultDetails(testResultDetails, testResult);
				} catch (Exception) {
					//                                cmdlet.WriteVerbose(cmdlet, eImportDetails);
				}
			}
            return importedTestResults;
		}

		List<ITestResultDetail> importTestResultDetails(IEnumerable<XElement> testResultDetails, ITestResult testResult)
		{
		    string lastTestResultDetailName = string.Empty;
		    var importedTestResultDetails = new List<ITestResultDetail>();
		    
			foreach (var singleDetail in testResultDetails) {
				lastTestResultDetailName = singleDetail.Attribute("name").Value;
				var detail = new TestResultDetail {
					TextDetail = singleDetail.Attribute("name").Value
				};
				string detailStatus = singleDetail.Attribute("status").Value;
				switch (detailStatus.ToUpper()) {
					case "FAILED":
						detail.DetailStatus = TestResultStatuses.Failed;
						break;
					case "PASSED":
						detail.DetailStatus = TestResultStatuses.Passed;
						break;
					case "KNOWNISSUE":
						detail.DetailStatus = TestResultStatuses.KnownIssue;
						break;
					case "NOTTESTED":
						detail.DetailStatus = TestResultStatuses.NotTested;
						break;
					default:
						detail.DetailStatus = TestResultStatuses.NotTested;
						break;
				}
				testResult.Details.Add(detail);
			}
		    return importedTestResultDetails;
		}
    }
}
