//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tmx.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tmx_Core_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tmx_Core_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tmx.Core.Tmx.Core.Resources", typeof(Tmx_Core_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmxLog.
        /// </summary>
        public static string LogName {
            get {
                return ResourceManager.GetString("LogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastTestRunId.
        /// </summary>
        public static string NewTestRun_lastTestRunId {
            get {
                return ResourceManager.GetString("NewTestRun_lastTestRunId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generated test result name.
        /// </summary>
        public static string TestData_AddTestResult_generated_test_result_name {
            get {
                return ResourceManager.GetString("TestData_AddTestResult_generated_test_result_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSOR_ARCHITECTURE.
        /// </summary>
        public static string TestPlatform_TestPlatform_PROCESSOR_ARCHITECTURE {
            get {
                return ResourceManager.GetString("TestPlatform_TestPlatform_PROCESSOR_ARCHITECTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform has been created automatically.
        /// </summary>
        public static string TestRun_TestRun_This_platform_has_been_created_automatically {
            get {
                return ResourceManager.GetString("TestRun_TestRun_This_platform_has_been_created_automatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_run_name.
        /// </summary>
        public static string TestRunCommand_testRunName_param {
            get {
                return ResourceManager.GetString("TestRunCommand_testRunName_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflow_name.
        /// </summary>
        public static string TestRunCommand_workflowName_param {
            get {
                return ResourceManager.GetString("TestRunCommand_workflowName_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for TestSuiteStatuses.
        /// </summary>
        public static string TestSuite_enStatus_Invalid_value_for_TestSuiteStatuses {
            get {
                return ResourceManager.GetString("TestSuite_enStatus_Invalid_value_for_TestSuiteStatuses", resourceCulture);
            }
        }
    }
}
