/*
 * Created by SharpDevelop.
 * User: Alexander Petrovskiy
 * Date: 17/02/2012
 * Time: 07:48 p.m.
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */

namespace Tmx
{
    using System;
    using System.Collections.Generic;
    using Core;
//    using System.ComponentModel;
    using System.Linq;
    using Core.Proxy;
    using Interfaces.Remoting;
    using Interfaces;
    using Interfaces.TestStructure;
    
    public delegate void TmxStructureChangedEventHandler(object sender, EventArgs e);
    public delegate void TmxDatabaseOperationCompletedEventHandler(object sender, EventArgs e);
    
    /// <summary>
    /// Description of TestSuitesCollection.
    /// </summary>
    // 20141014
    public static class TestData
    // public class TestData
    {
        // ----------------- Variables ---------------------------
        
        public const string TestStateNotTested = "NOT TESTED";
        public const string TestStatePassed = "PASSED";
        public const string TestStateFailed = "FAILED";
        public const string TestStateKnownIssue = "KNOWN ISSUE";
        
        public const string Autogenerated = "autogenerated";
        public const string DefaultPlatformName = "default platform";
        public const string DefaultPlatformId = "1";
        
        internal static bool AlreadyInitialized { get; set; }
        
        static TestData()
        // public TestData()
        {
            TestSuites = new List<ITestSuite>();
            TestPlatforms = new List<ITestPlatform>();
            ExcludeList = new List<string>();
            AddDefaultPlatform();
        }
        
        // ----------------- Properties --------------------------
        
        public static List<ITestSuite> TestSuites {get; internal set; }
        
        public static ITestSuite CurrentTestSuite { get; set; }
        public static ITestScenario CurrentTestScenario { get; set; }
        public static ITestResult CurrentTestResult { get; set; } // ?? rewrite as the last item of the collection ??
        public static ITestCase CurrentTestCase { get; set; }
        public static List<ITestPlatform> TestPlatforms {get; internal set; }
        public static ITestPlatform CurrentTestPlatform { get; set; }
        public static ITestResult LastTestResult // ?? rewrite as setting the previous on creating the current ??
        {
            get {
                ITestResult testResult = null;
                if (null != TestSuites && 0 < TestSuites.Count) {
                    
                    int suiteNumber = TestSuites.Count - 1;
                    
                    if (null != TestSuites[suiteNumber].TestScenarios &&
                        0 < TestSuites[suiteNumber].TestScenarios.Count) {
                        
                        int scenarioNumber = TestSuites[TestSuites.Count -1].TestScenarios.Count - 1;
                        
                        if (null != TestSuites[suiteNumber].TestScenarios[scenarioNumber].TestResults &&
                            0 < TestSuites[suiteNumber].TestScenarios[scenarioNumber].TestResults.Count) {
                            
                        testResult = TestSuites[suiteNumber].TestScenarios[scenarioNumber].TestResults[
                                TestSuites[suiteNumber].TestScenarios[scenarioNumber].TestResults.Count - 1];
                        }
                    }
                }
                
                return testResult;
            }
        }
        
        public static IDatabase CurrentStructureDB { get; set; }
        public static IDatabase CurrentRepositoryDB { get; set; }
        public static IDatabase CurrentResultsDB { get; set; }
        public static List<string> ExcludeList { get; set; }

        // ------------------ Events -----------------------------
        public static event TmxStructureChangedEventHandler TmxNewTestSuiteCreated;
        public static event TmxStructureChangedEventHandler TmxTestSuiteOpened;
        public static event TmxStructureChangedEventHandler TmxNewTestScenarioAdded;
        public static event TmxStructureChangedEventHandler TmxTestScenarioOpened;
        public static event TmxStructureChangedEventHandler TmxNewTestResultClosed;
        public static event TmxStructureChangedEventHandler TmxNewTestResultDetailAdded;
        public static event TmxStructureChangedEventHandler TmxNewTestPlatformCreated;
        
        public static event TmxDatabaseOperationCompletedEventHandler TmxBackUpTestResultsCompleted;
        public static event TmxDatabaseOperationCompletedEventHandler TmxRestoreTestResultsCompleted;
        
        public static event TmxDatabaseOperationCompletedEventHandler TmxTestBucketAdded;
        public static event TmxDatabaseOperationCompletedEventHandler TmxTestBucketRemoved;
        public static event TmxDatabaseOperationCompletedEventHandler TmxTestBucketChanged;
        
        public static event TmxDatabaseOperationCompletedEventHandler TmxTestConstantAdded;
        public static event TmxDatabaseOperationCompletedEventHandler TmxTestConstantRemoved;
        public static event TmxDatabaseOperationCompletedEventHandler TmxTestConstantChanged;
        
        public static event TmxDatabaseOperationCompletedEventHandler TmxTestCaseAdded;
        public static event TmxDatabaseOperationCompletedEventHandler TmxTestCaseRemoved;
        public static event TmxDatabaseOperationCompletedEventHandler TmxTestCaseChanged;
        
        internal static void OnTmxNewTestSuiteCreated(object sender, EventArgs e) 
        {
            if (TmxNewTestSuiteCreated != null)
                TmxNewTestSuiteCreated(sender, e);
        }
        
        internal static void OnTmxTestSuiteOpened(object sender, EventArgs e) 
        {
            if (TmxTestSuiteOpened != null)
                TmxTestSuiteOpened(sender, e);
        }
        
        internal static void OnTmxNewTestScenarioAdded(object sender, EventArgs e) 
        {
            if (TmxNewTestScenarioAdded != null)
                TmxNewTestScenarioAdded(sender, e);
        }
        
        internal static void OnTmxTestScenarioOpened(object sender, EventArgs e) 
        {
            if (TmxTestScenarioOpened != null)
                TmxTestScenarioOpened(sender, e);
        }
        
        internal static void OnTmxNewTestResultClosed(object sender, EventArgs e) 
        {
            if (TmxNewTestResultClosed != null)
                TmxNewTestResultClosed(sender, e);
        }
        
        internal static void OnTmxNewTestResultDetailAdded(object sender, EventArgs e) 
        {
            if (TmxNewTestResultDetailAdded != null)
                TmxNewTestResultDetailAdded(sender, e);
        }
        
        internal static void OnTmxBackUpTestResultsCompleted(object sender, EventArgs e) 
        {
            if (TmxBackUpTestResultsCompleted != null)
                TmxBackUpTestResultsCompleted(sender, e);
        }
        
        internal static void OnTmxRestoreTestResultsCompleted(object sender, EventArgs e) 
        {
            if (TmxRestoreTestResultsCompleted != null)
                TmxRestoreTestResultsCompleted(sender, e);
        }
        
        internal static void OnTmxNewTestPlatformCreated(object sender, EventArgs e) 
        {
            if (TmxNewTestPlatformCreated != null)
                TmxNewTestPlatformCreated(sender, e);
        }
        
        internal static void OnTmxTestBucketAdded(object sender, EventArgs e) 
        {
            if (TmxTestBucketAdded != null)
                TmxTestBucketAdded(sender, e);
        }
        
        internal static void OnTmxTestBucketRemoved(object sender, EventArgs e) 
        {
            if (TmxTestBucketRemoved != null)
                TmxTestBucketRemoved(sender, e);
        }
        
        internal static void OnTmxTestBucketChanged(object sender, EventArgs e) 
        {
            if (TmxTestBucketChanged != null)
                TmxTestBucketChanged(sender, e);
        }
        
        internal static void OnTmxTestConstantAdded(object sender, EventArgs e) 
        {
            if (TmxTestConstantAdded != null)
                TmxTestConstantAdded(sender, e);
        }
        
        internal static void OnTmxTestConstantRemoved(object sender, EventArgs e) 
        {
            if (TmxTestConstantRemoved != null)
                TmxTestConstantRemoved(sender, e);
        }
        
        internal static void OnTmxTestConstantChanged(object sender, EventArgs e) 
        {
            if (TmxTestConstantChanged != null)
                TmxTestConstantChanged(sender, e);
        }
        
        internal static void OnTmxTestCaseAdded(object sender, EventArgs e) 
        {
            if (TmxTestCaseAdded != null)
                TmxTestCaseAdded(sender, e);
        }
        
        internal static void OnTmxTestCaseRemoved(object sender, EventArgs e) 
        {
            if (TmxTestCaseRemoved != null)
                TmxTestCaseRemoved(sender, e);
        }
        
        internal static void OnTmxTestCaseChanged(object sender, EventArgs e) 
        {
            if (TmxTestCaseChanged != null)
                TmxTestCaseChanged(sender, e);
        }
        
        // ------------------ Methods ----------------------------
        public static void ResetData()
        {
            if (null != TestSuites) TestSuites.Clear();
//            // 20141117
//            if (null != TestPlatforms) TestPlatforms.Clear();
            CurrentTestResult = null;
            CurrentTestScenario = null;
            CurrentTestSuite = null;
//            try {
            InitTestData();
//            }
//            catch (Exception ee) {
//                Console.WriteLine(ee.Message);
//            }
        }
        
        public static void ResetDataFull()
        {
            ResetData();
            if (null != TestPlatforms) TestPlatforms.Clear();
        }
        
        public static void CleanData()
        {
            if (null != TestSuites) {
                foreach (var suite in TestSuites) {
                    if (null != suite.TestScenarios) {
                        foreach (var scenario in suite.TestScenarios) {
                            scenario.TestResults.Clear();
                            scenario.enStatus = TestStatuses.NotRun;
                        }
                    }
                    suite.enStatus = TestStatuses.NotRun;
                }
            }
            CurrentTestResult = null;
            CurrentTestScenario = null;
            CurrentTestSuite = null;
        }
        
        // 20160116
        internal static void AddTestResult(string closingTestResultName, // previousTestResultName
                                           string closingTestResultId, // previousTestResultId
                                           bool? passed,
                                           bool isKnownIssue,
                                           bool generateNextResult,
                                           // 20160116
                                           // InvocationInfo myInvocation,
                                           // ErrorRecord error,
                                           Exception error,
                                           string testResultDescription,
                                           TestResultOrigins origin,
                                           bool skipAutomatic)
        {
            //TestData.InitCurrentTestScenario();
            
            bool generated = TestResultOrigins.Automatic == origin;
            
            ITestResult currentTestResult;
            if (null != CurrentTestResult) {
                currentTestResult = CurrentTestResult;
            } else {
                // 20141204
//                currentTestResult =
//                    new TestResult(
//                        TestData.CurrentTestScenario.Id,
//                        TestData.CurrentTestSuite.Id);
                currentTestResult =
                    new TestResult(
                        CurrentTestScenario.Id,
                        CurrentTestSuite.Id) {
                    SuiteUniqueId = CurrentTestSuite.UniqueId,
                    ScenarioUniqueId = CurrentTestScenario.UniqueId
                };
            }
            
            if (string.IsNullOrEmpty(currentTestResult.Name)) {
                
//                if (closingTestResultName != null &&
//                    closingTestResultName != string.Empty &&
//                    closingTestResultName.Length > 0 &&
//                    TestData.CurrentTestResult != null && 
//                     closingTestResultName != TestData.CurrentTestResult.Name) {

                if (!string.IsNullOrEmpty(closingTestResultName) &&
                    ((CurrentTestResult != null && 
                      closingTestResultName != CurrentTestResult.Name) ||
                      null == CurrentTestResult)) {
                    
                    currentTestResult.Name = closingTestResultName;
                } else {
                    currentTestResult.Name = Resources.TestData_AddTestResult_generated_test_result_name;
                }
                
            } else {
                // the current test result is a result that was preset
                // nothing to do
            }

            // setting test result's origin
            //if (generated)
            //    currentTestResult.SetOrigin(TestResultOrigins.Automatic);
            //else
            //    currentTestResult.SetOrigin(origin);
            currentTestResult.SetOrigin(generated ? TestResultOrigins.Automatic : origin);

            if (string.IsNullOrEmpty(currentTestResult.Id)) {
                
                if (!string.IsNullOrEmpty(closingTestResultId) &&
                    ((null != CurrentTestResult &&
                    closingTestResultId != CurrentTestResult.Id) ||
                    null == CurrentTestResult))
                    currentTestResult.Id = closingTestResultId;
                else
                    currentTestResult.Id = GetTestResultId();
            } else {
                // there already was the Id
                // nothing to do
            }
            
            if (passed != null) {
                if ((bool)passed) {
                    currentTestResult.enStatus = TestStatuses.Passed;
                } else {
                    currentTestResult.enStatus = TestStatuses.Failed;
                }

                if (isKnownIssue) {
                    currentTestResult.enStatus = TestStatuses.KnownIssue;
                }
            } else {
                //currentTestResult.enStatus = TestResultStatuses.NotTested;
                
                // if there were no errors during the test case execution
                // it is marked as passed
                bool noErrors = true;
                if (null == currentTestResult.Error &&
                    TestStatuses.Failed != currentTestResult.enStatus &&
                    TestStatuses.KnownIssue != currentTestResult.enStatus) {
                    
                    //foreach (ITestResultDetail detail in currentTestResult.Details) {
                    //    if (null == ((TestResultDetail)detail).ErrorDetail) {
                    //        noErrors = false;
                    //        break;
                    //    }
                    //}
                    if (currentTestResult.Details.Any(detail => null == ((TestResultDetail) detail).ErrorDetail))
                        noErrors = false;
                }
                
                if (noErrors && null != passed) {
                    currentTestResult.enStatus = TestStatuses.Passed;
                }

            }
            
            if (!string.IsNullOrEmpty(testResultDescription)) {
                currentTestResult.Description = testResultDescription;
            }
            
            if (generated)
                currentTestResult.SetGenerated();
            
            if (TmxHelper.TestCaseStarted == DateTime.MinValue)
                TmxHelper.TestCaseStarted = DateTime.Now;

            currentTestResult.SetNow();
            currentTestResult.SetTimeSpent(
                (currentTestResult.Timestamp - TmxHelper.TestCaseStarted).TotalSeconds);
            
            CurrentTestResult = currentTestResult;
            
            try {
                CurrentTestResult.PlatformUniqueId = CurrentTestScenario.PlatformUniqueId;
                CurrentTestResult.PlatformId = CurrentTestScenario.PlatformId;
                // 20141204
                CurrentTestResult.SuiteUniqueId = CurrentTestSuite.UniqueId;
                CurrentTestResult.ScenarioUniqueId = CurrentTestScenario.UniqueId;
            }
            catch {}
            
            if (null != CurrentTestScenario.TestResults[CurrentTestScenario.TestResults.Count - 1] &&
                TestResultOrigins.Logical == CurrentTestScenario.TestResults[CurrentTestScenario.TestResults.Count - 1].Origin &&
                CurrentTestScenario.TestResults[CurrentTestScenario.TestResults.Count - 1] != CurrentTestResult &&
                !string.IsNullOrEmpty(CurrentTestScenario.TestResults[CurrentTestScenario.TestResults.Count - 1].Name)) {
                
                TmxHelper.TestCaseStarted = DateTime.Now;
                // 20141204
                // TestData.CurrentTestScenario.TestResults.Add(new TestResult(TestData.CurrentTestScenario.Id, TestData.CurrentTestSuite.Id));
                CurrentTestScenario.TestResults.Add(new TestResult(CurrentTestScenario.Id, CurrentTestSuite.Id) {
                                                                 SuiteUniqueId = CurrentTestSuite.UniqueId,
                                                                 ScenarioUniqueId = CurrentTestScenario.UniqueId
                                                             });
            }

            /*
            if (null != TestData.CurrentTestScenario.TestResults[TestData.CurrentTestScenario.TestResults.Count - 1] &&
                TestResultOrigins.Logical == TestData.CurrentTestScenario.TestResults[TestData.CurrentTestScenario.TestResults.Count - 1].Origin &&
                TestData.CurrentTestScenario.TestResults[TestData.CurrentTestScenario.TestResults.Count - 1] != TestData.CurrentTestResult &&
                null != TestData.CurrentTestScenario.TestResults[TestData.CurrentTestScenario.TestResults.Count - 1].Name &&
                0 < TestData.CurrentTestScenario.TestResults[TestData.CurrentTestScenario.TestResults.Count - 1].Name.Length) {
                
                TmxHelper.TestCaseStarted =
                    System.DateTime.Now;
                TestData.CurrentTestScenario.TestResults.Add(new TestResult(TestData.CurrentTestScenario.Id, TestData.CurrentTestSuite.Id));
               
            }
            */

            CurrentTestScenario.TestResults[CurrentTestScenario.TestResults.Count - 1] = 
                CurrentTestResult;
            
            #region Test Result's PowerShell data
            // 20160116
            /*
            if (myInvocation != null) {
                TestData.CurrentTestResult.SetScriptName(TmxHelper.GetScriptName(myInvocation));
                TestData.CurrentTestResult.SetLineNumber(TmxHelper.GetScriptLineNumber(myInvocation));
                TestData.CurrentTestResult.SetPosition(TmxHelper.GetPipelinePosition(myInvocation));
                // 20130329
                try {
                    
                    if (((bool)passed && Preferences.LogScriptName_Passed) || (!(bool)passed && Preferences.LogScriptName_Failed)) {
                        
                        TestData.CurrentTestResult.Code += 
                            "script name: " + 
                            TestData.CurrentTestResult.ScriptName;
    
                    }
                }
                catch {}
                try {
                    
                    if (((bool)passed && Preferences.LogLineNumber_Passed) || (!(bool)passed && Preferences.LogLineNumber_Failed)) {
                        
                        TestData.CurrentTestResult.Code +=
                            "\r\nline number: " +
                            TestData.CurrentTestResult.LineNumber.ToString();
    
                    }
                }
                catch {}
                try {
                    
                    if (((bool)passed && Preferences.LogCode_Passed) || (!(bool)passed && Preferences.LogCode_Failed)) {
                        
                        TestData.CurrentTestResult.Code +=
                            "\r\ncode:\r\n" +
                            myInvocation.Line;
    
                    }
                }
                catch {}
            }
            
            if (error != null) {
                // 20150116
                // TestData.CurrentTestResult.SetError(error);
                TestData.CurrentTestResult.SetError(error.Exception);
            }
            */
            #endregion Test Result's PowerShell data
            
            var sourceTestResult = CurrentTestResult;
            SetScenarioStatus(skipAutomatic);
            SetSuiteStatus(skipAutomatic);
            
            if (generateNextResult) {
                // write current time
                TmxHelper.TestCaseStarted = DateTime.Now;
                CurrentTestScenario.TestResults.Add(
                    new TestResult(
                       CurrentTestScenario.Id,
                       CurrentTestScenario.SuiteId) { SuiteUniqueId = CurrentTestScenario.SuiteUniqueId, ScenarioUniqueId = CurrentTestScenario.UniqueId });
                CurrentTestResult = 
                    CurrentTestScenario.TestResults[CurrentTestScenario.TestResults.Count - 1];
            } else {
                // write zero time
                TmxHelper.TestCaseStarted = DateTime.MinValue;
                CurrentTestResult = null;
            }
            
            if (Preferences.Storage) {
                using (var session = StorageHelper.SessionFactory.OpenSession())
                {
                    session.Save(CurrentTestResult);
                }
            }

            OnTmxNewTestResultClosed(sourceTestResult, null);
        }
        
        internal static void InitTestData()
        {
            if (AlreadyInitialized) return;
            
            TmxHelper.TestCaseStarted = DateTime.Now;
            
            if (null == TestSuites)
                TestSuites = new List<ITestSuite>();
            if (null == TestPlatforms)
                TestPlatforms = new List<ITestPlatform>();
            
            // check that at least one platform exists
            if (0 == TestPlatforms.Count)
                AddDefaultPlatform();
            /*
            if (0 == TestData.TestPlatforms.Count) {
                TmxHelper.NewTestPlatform(
                    // 20140716
                    // "autogenerated",
                    TestData.Autogenerated,
                    GetTestPlatformId(),
                    "This platform has been created automatically",
                    Environment.OSVersion.Platform.ToString(),
                    Environment.OSVersion.VersionString,
                    Environment.GetEnvironmentVariable("PROCESSOR_ARCHITECTURE"),
                    "");
            }
            */
            
            // check that at least one suite exists
            if (TestSuites.Count == 0)
                TmxHelper.NewTestSuite(
                    Autogenerated,
                    GetTestSuiteId(),
                    CurrentTestPlatform.UniqueId,
                    "This suite has been created automatically",
                    null,
                    null);
            
            // check that at least one scenario exists
            if (CurrentTestSuite.TestScenarios.Count == 0)
                CreateAutogeneratedTestScenario();
            
            AlreadyInitialized = true;
        }
        
        internal static void AddDefaultPlatform()
        {
            try {
                if (null != TestPlatforms && 0 < TestPlatforms.Count && TestPlatforms.Any(tp => tp.Id == DefaultPlatformId && tp.Name == DefaultPlatformName))
                    return;
            TmxHelper.NewTestPlatform(
                DefaultPlatformName,
                DefaultPlatformId,
                "This platform has been created automatically",
                Environment.OSVersion.Platform.ToString(),
                Environment.OSVersion.VersionString,
                Environment.GetEnvironmentVariable("PROCESSOR_ARCHITECTURE"), "");
            }
            catch (Exception ee) {
                Console.WriteLine(ee.Message);
            }
        }
        
        internal static string GetDefaultPlatformId()
        {
            return GetTestPlatform(DefaultPlatformName, DefaultPlatformId).Id;
        }
        
        internal static Guid GetDefaultPlatformUniqueId()
        {
            return GetTestPlatform(DefaultPlatformName, DefaultPlatformId).UniqueId;
        }
        
        internal static void CreateAutogeneratedTestScenario()
        {
            var dataObject = new AddScenarioCmdletBaseDataObject {
                Name = Autogenerated,
                Id = GetTestScenarioId(),
                Description = "This scenario has been created automatically",
                TestSuiteName = CurrentTestSuite.Name,
                TestSuiteId = CurrentTestSuite.Id,
                InputObject = CurrentTestSuite,
                TestPlatformId = CurrentTestPlatform.Id,
                TestPlatformUniqueId = CurrentTestPlatform.UniqueId
            };
            TmxHelper.AddTestScenario(dataObject);
        }
        
        internal static void InitCurrentTestSuite()
        {
            if (null == CurrentTestSuite) {
                
                if (null == TestSuites) {
                    
//                    try {
                    InitTestData();
//                    }
//                    catch (Exception ee) {
//                        Console.WriteLine(ee.Message);
//                    }
                } else {
                    
                    if (0 == TestSuites.Count) {
                        
                        AddTestSuite(
                            Autogenerated,
                            GetTestSuiteId(),
                            CurrentTestPlatform.UniqueId,
                            string.Empty,
                            null,
                            null);
                    }
                }
                
                CurrentTestSuite = TestSuites[TestSuites.Count - 1];
            }
        }
        
        internal static void InitCurrentTestScenario()
        {
            if (null == CurrentTestSuite)
                InitCurrentTestSuite();
            
            if (null == CurrentTestScenario) {
                
                if (null == CurrentTestSuite.TestScenarios)
                    // that's impossible...
                    CurrentTestSuite.TestScenarios = new List<ITestScenario>();
                                
                if (0 == CurrentTestSuite.TestScenarios.Count) {
                    
                    AddTestScenario(
                        CurrentTestSuite,
                        Autogenerated,
                        GetTestScenarioId(),
                        string.Empty,
                        string.Empty,
                        string.Empty,
                        CurrentTestPlatform.UniqueId,
                        null,
                        null);
                }
                
                CurrentTestScenario =
                    (TestScenario)CurrentTestSuite.TestScenarios[
                        CurrentTestSuite.TestScenarios.Count - 1];
            }
        }
        
        internal static void SetScenarioStatus(bool skipAutomatic)
        {
            if (null == CurrentTestScenario) {
                InitCurrentTestScenario();
            }
            
            int counterPassedResults = 0;
            int counterKnownIssueResults = 0;
            
            if (null != CurrentTestScenario &&
                null != CurrentTestScenario.TestResults &&
                0 < CurrentTestScenario.TestResults.Count) {
                foreach (var testResult in CurrentTestScenario.TestResults)
                    switch (testResult.enStatus) {
                        case TestStatuses.Passed:
                            counterPassedResults++;
                            // 20131001
                            //TestData.CurrentTestScenario.enStatus = TestScenarioStatuses.Passed;
                            if (TestStatuses.Failed != CurrentTestScenario.enStatus)
                                CurrentTestScenario.enStatus = TestStatuses.Passed;
                            break;
                        case TestStatuses.Failed:
                            CurrentTestScenario.enStatus = TestStatuses.Failed;
                            return;
                    //break;
                        case TestStatuses.NotRun:
                            
                            break;
                        case TestStatuses.KnownIssue:
                            counterKnownIssueResults++;
                            // 20131001
                            //TestData.CurrentTestScenario.enStatus = TestScenarioStatuses.Passed;
                            if (TestStatuses.Failed != CurrentTestScenario.enStatus)
                                CurrentTestScenario.enStatus = TestStatuses.Passed;
                            break;
                        default:
                            throw new Exception("Invalid value for TestResultStatuses");
                    }
                if (0 == counterPassedResults && 0 < counterKnownIssueResults)
                    CurrentTestScenario.enStatus = TestStatuses.KnownIssue;
            
                // set statistics
                // 20150925
                // var testStatistics = new TestStatistics();
                var testStatistics = ProxyFactory.Get<TestStatistics>();
                testStatistics.RefreshScenarioStatistics(CurrentTestScenario, skipAutomatic);
            }
        }
        
        internal static void SetSuiteStatus(bool skipAutomatic)
        {
            if (null == CurrentTestSuite)
                InitCurrentTestScenario();
            
            SetScenarioStatus(skipAutomatic);
            
            int counterPassedResults = 0;
            int counterKnownIssueResults = 0;
            
            if (CurrentTestSuite != null && 
                0 < CurrentTestSuite.TestScenarios.Count) {
                
                foreach (var scenario in CurrentTestSuite.TestScenarios) {
                    
                    switch (scenario.enStatus) {
                        case TestStatuses.Passed:
                            counterPassedResults++;
                            if (TestStatuses.Failed != CurrentTestSuite.enStatus)
                                CurrentTestSuite.enStatus = TestStatuses.Passed;
                            break;
                        case TestStatuses.Failed:
                            CurrentTestSuite.enStatus = TestStatuses.Failed;
                            return;
                        case TestStatuses.NotRun:
                            break;
                        case TestStatuses.KnownIssue:
                            counterKnownIssueResults++;
                            if (TestStatuses.Failed != CurrentTestSuite.enStatus)
                                CurrentTestSuite.enStatus = TestStatuses.Passed;
                            break;
                        default:
                            // 20130428
                            //throw new Exception("Invalid value for TestScenarioStatuses");
                            // as Not Tested
                            break;
                    }
                }
                
                if (0 == counterPassedResults && 0 < counterKnownIssueResults)
                    CurrentTestSuite.enStatus = TestStatuses.KnownIssue;
                
                // set statistics
                // 20150925
                // var testStatistics = new TestStatistics();
                var testStatistics = ProxyFactory.Get<TestStatistics>();
                testStatistics.RefreshSuiteStatistics(CurrentTestSuite, skipAutomatic);
            }
        }
        
        internal static string GetTestPlatformId()
        {
            string result = string.Empty;            
            
            // read the last id used and generate a new one
            int testNumber = TestPlatforms.Count; // + 1;
            bool noValidId = true;
            do {
                foreach (var Platform in TestPlatforms) {
                    if (Platform.Id == testNumber.ToString()) {
                        testNumber++;
                    }
                }
                noValidId = false;
                result = testNumber.ToString();
            } while (noValidId);
            
            return result;
        }
        
        internal static string GetTestSuiteId()
        {
            string result = string.Empty;            
            
            // read the last id used and generate a new one
            int testNumber = null != TestSuites ? TestSuites.Count : 1;
            bool noValidId = true;
            do {
                foreach (var suite in TestSuites) {
                    if (suite.Id == testNumber.ToString()) {
                        testNumber++;
                    }
                }
                // TestData.TestSuites.Select(ts => ts.Id == testNumber.Where(ts => ts.Id == testNumber).ForEach(ts => ts == testNumber ? testNumber++ : continue }
                noValidId = false;
                result = testNumber.ToString();
            } while (noValidId);
            
            return result;
        }
        
        internal static string GetTestScenarioId()
        {
            string result = string.Empty;            
            
            int scenarioNumber = 1;
            if (null != TestSuites && 0 < TestSuites.Count) {

                if (null != CurrentTestSuite.TestScenarios) {

                    // read the last used id and generate a new one
                    scenarioNumber = 
                        CurrentTestSuite.TestScenarios.Count; // + 1;
                    bool noValidId = true;

                    do {
                        foreach (var scenario in CurrentTestSuite.TestScenarios)
                            if (scenario.Id == scenarioNumber.ToString())
                                scenarioNumber++;
                        noValidId = false;
                        if (0 == scenarioNumber)
                            scenarioNumber++;
                        result = scenarioNumber.ToString();
                    } while (noValidId);
                } else
                    result = scenarioNumber.ToString();
            } else
                result = scenarioNumber.ToString();
            return result;
        }
        
        internal static string GetTestResultId()
        {
            string result = string.Empty;
            
            int testNumber = 0;
            if (null != TestSuites && 0 < TestSuites.Count) {
                
                if (null != CurrentTestScenario) {
                    
                    if (null != CurrentTestScenario.TestResults) {
                        
                        // read the last used id and generate a new one
                        testNumber = 
                            CurrentTestScenario.TestResults.Count; // + 1;
                        bool noValidId = true;
                        do {
                            foreach (var testResult in CurrentTestScenario.TestResults)
                                if (testResult.Id == testNumber.ToString())
                                    testNumber++;
                            noValidId = false;
                            result = testNumber.ToString();
                        } while (noValidId);
                        
                    } else
                        result = testNumber.ToString();
                } else
                    result = testNumber.ToString();
            } else
                result = testNumber.ToString();
            return result;
        }
        
//        internal static bool AttachTestResultCode()
//        {
//            bool result = false;
//            
//            
//            
//            return result;
//        }
        
        internal static void AddTestResultTextDetail(ITestResultDetailCmdletBaseDataObject cmdlet, object detail)
        {
            ITestResultDetail testResultDetail = 
                new TestResultDetail();
            
            testResultDetail.AddTestResultDetail(
                TestResultDetailTypes.Comment,
                detail.ToString());
            CurrentTestResult.Details.Add(testResultDetail);
            
            testResultDetail.DetailStatus = cmdlet.TestResultStatus;
            
            switch (cmdlet.TestResultStatus) {
                case TestStatuses.Failed:
                    if (TestStatuses.KnownIssue != CurrentTestResult.enStatus)
                        CurrentTestResult.enStatus = TestStatuses.Failed;
                    break;
                case TestStatuses.Passed:
                    if (TestStatuses.KnownIssue != CurrentTestResult.enStatus &&
                        TestStatuses.Failed != CurrentTestResult.enStatus)
                        CurrentTestResult.enStatus = TestStatuses.Passed;
                    break;
                case TestStatuses.NotRun:
                    // nothing to do
                    break;
                case TestStatuses.KnownIssue:
                    CurrentTestResult.enStatus = TestStatuses.KnownIssue;
                    break;
                default:
//                    cmdlet.WriteVerbose(cmdlet, "TestResultStatus = ????");
//                    cmdlet.WriteVerbose(cmdlet, cmdlet.TestResultStatus.ToString());
                    break;
            }
            
            OnTmxNewTestResultDetailAdded(testResultDetail, null);
            
            if (cmdlet.Finished) {
                
                TmxHelper.TestCaseStarted = DateTime.Now;
                
                // 20130621                
//                TestData.CurrentTestScenario.TestResults.Add(new TestResult(TestData.CurrentTestScenario.Id, TestData.CurrentTestSuite.Id));
//                TestData.CurrentTestScenario.TestResults[TestData.CurrentTestScenario.TestResults.Count - 1] =
//                    TestData.CurrentTestResult;
                // 20130621
                ITestResult newTestResult = new TestResult(CurrentTestScenario.Id, CurrentTestSuite.Id);
                if (CurrentTestResult == CurrentTestScenario.TestResults[CurrentTestScenario.TestResults.Count - 1]) {
                    // autogeneration + Close-TmxTestResult
                    CurrentTestScenario.TestResults.Add(newTestResult);
                    CurrentTestResult = CurrentTestScenario.TestResults[CurrentTestScenario.TestResults.Count - 1];
                } else {
                    // Set-TmxCurrentTestResult + any closing
                    CurrentTestScenario.TestResults.Add(CurrentTestResult);
                    CurrentTestResult = newTestResult;
                }
            }
        }
        
        // 20160116
        // internal static void AddTestResultErrorDetail(ErrorRecord detail)
        internal static void AddTestResultErrorDetail(Exception detail)
        {
            var testResultDetail = new TestResultDetail();
            
            testResultDetail.AddTestResultDetail(
                TestResultDetailTypes.ErrorRecord,
                detail);
            CurrentTestResult.Details.Add(testResultDetail);
        }
        
        internal static void AddTestResultScreenshotDetail(object detail)
        {
            var testResultDetail = new TestResultDetail();
            
            testResultDetail.AddTestResultDetail(
                TestResultDetailTypes.Screenshot,
                detail.ToString());
            CurrentTestResult.Details.Add(testResultDetail);
            CurrentTestResult.SetScreenshot(detail.ToString());
        }
        
        internal static bool AddTestPlatform(
            string testPlatformName,
            string testPlatformId,
            string testPlatformDesctiption,
            string testPlatformOS,
            string testPlatformVersion,
            string testPlatformArchitecture,
            string testPlatformLanguage)
        {
            bool result = false;
            
            if (string.IsNullOrEmpty(testPlatformId))
                testPlatformId = GetTestPlatformId();
            
            var alreadyExistingTestPlatform = GetTestPlatform(testPlatformName, testPlatformId);
            if (null != alreadyExistingTestPlatform) {
                CurrentTestPlatform = alreadyExistingTestPlatform;
                // the test platform requested won't be duplicated, exit
                return false;
            }
            
            var testPlatform = new TestPlatform {
                Id = testPlatformId,
                Name = testPlatformName,
                OperatingSystem = testPlatformOS,
                Version = testPlatformVersion,
                Architecture = testPlatformArchitecture,
                Language = testPlatformLanguage,
                Description = testPlatformDesctiption
            };
            TestPlatforms.Add(testPlatform);
            
            CurrentTestPlatform = 
                TestPlatforms[TestPlatforms.Count - 1];
            
            if (CurrentTestPlatform != null)
                OnTmxNewTestPlatformCreated(CurrentTestPlatform, new EventArgs()); //null);
            
            if (Preferences.Storage) {
                using (var session = StorageHelper.SessionFactory.OpenSession()) {
                    session.Save(CurrentTestPlatform);
                }
            }
            
            result = true;
            return result;
        }
        
        internal static bool AddTestSuite(string testSuiteName, 
                                          string testSuiteId,
                                          Guid testPlatformId,
                                          string testSuiteDesctiption,
                                          ICodeBlock[] testSuiteBeforeScenario,
                                          ICodeBlock[] testSuiteAfterScenario)
        {
            bool result = false;
            
            if (string.IsNullOrEmpty(testSuiteId))
                testSuiteId = GetTestSuiteId();
            
            if (null != GetTestSuite(testSuiteName, testSuiteId, testPlatformId))
                // the suite requested won't be duplicated, exit
                return false;
            
            // removing the first (autogenerated) suite
            try {
                if (null == TestSuites)
                    TestSuites = new List<ITestSuite>();
                // 20141117
                // probably useful
//                if (1 == TestData.TestSuites.Count && TestData.Autogenerated == TestData.TestSuites[0].Name &&
//                                1 == TestData.TestSuites[0].TestScenarios.Count && TestData.Autogenerated == TestData.TestSuites[0].TestScenarios[0].Name &&
//                                1 == TestData.TestSuites[0].TestScenarios[0].TestResults.Count && TestResultOrigins.Automatic == TestData.TestSuites[0].TestScenarios[0].TestResults[0].Origin) {
                if (1 == TestSuites.Count && TestSuites.All(ts => ts.Name == Autogenerated))
                    TestSuites.RemoveAt(0);
            } catch (Exception ee) {
                Console.WriteLine(ee.Message);
            }
            
            // set time spent on the previous suite
            if (null != CurrentTestSuite) {
                
                if (DateTime.MinValue != CurrentTestSuite.Timestamp) {
                    
                    CurrentTestSuite.SetTimeSpent(
                        CurrentTestSuite.TimeSpent +=
                        (DateTime.Now - CurrentTestSuite.Timestamp).TotalSeconds);
                    
                    CurrentTestSuite.Timestamp = DateTime.MinValue;
                }
            }
            
            TestSuites.Add(new TestSuite(testSuiteName, testSuiteId));
            if (!string.IsNullOrEmpty(testSuiteDesctiption))
                TestSuites[TestSuites.Count - 1].Description = testSuiteDesctiption;
            
            CurrentTestSuite = TestSuites[TestSuites.Count - 1];
            
            if (CurrentTestSuite != null) {
                
                CurrentTestSuite.PlatformUniqueId = testPlatformId != Guid.Empty ? testPlatformId : CurrentTestPlatform.UniqueId;
                CurrentTestSuite.PlatformId = TestPlatforms.First(tp => tp.UniqueId == CurrentTestSuite.PlatformUniqueId).Id;
                CurrentTestSuite.BeforeScenario = testSuiteBeforeScenario;
                CurrentTestSuite.AfterScenario = testSuiteAfterScenario;
                
                // set the initial time for this suite's session
                CurrentTestSuite.SetNow();
                
                OnTmxNewTestSuiteCreated(CurrentTestSuite, new EventArgs()); //null);
            }
            
            if (Preferences.Storage) {
                using (var session = StorageHelper.SessionFactory.OpenSession()) {
                    session.Save(CurrentTestSuite);
                }
            }
            
            if (0 == CurrentTestSuite.TestScenarios.Count)
                CreateAutogeneratedTestScenario();
            
            result = true;
            return result;
        }
        
        internal static ITestPlatform GetTestPlatform(Guid testPlatformId)
        {
            return TestPlatforms.FirstOrDefault(tp => tp.UniqueId == testPlatformId);
        }
        
        // 20141114
        internal static ITestPlatform GetTestPlatform(string testPlatformName, string testPlatformId)
        // internal static ITestPlatform GetTestPlatform(string testPlatformName, Guid testPlatformId)
        {
            if (null == TestPlatforms || 0 == TestPlatforms.Count) return null;
            
            ITestPlatform result = null;
            
            if (!string.IsNullOrEmpty(testPlatformName)) {
                foreach (var testPlatform in TestPlatforms.Where(tp => tp.Name == testPlatformName)) {
                    
                    // id does not match
                    if (!string.IsNullOrEmpty(testPlatformId) && testPlatformId != testPlatform.Id)
                        continue;
                    
                    if (!string.IsNullOrEmpty(testPlatformId) && testPlatformId == testPlatform.Id)
                        result = testPlatform;
                    
                    if (string.IsNullOrEmpty(testPlatformId))
                        result = testPlatform;
                    
                    if (result != null)
                        return result;
                }
            }
            
            return !string.IsNullOrEmpty(testPlatformId) ? TestPlatforms.FirstOrDefault(testPlatform => testPlatform.Id == testPlatformId) : result;
            
            /*
            if (!string.IsNullOrEmpty(testPlatformId)) {
                // 20140902
//                foreach (var testPlatform in TestPlatforms.Where(testPlatform => testPlatform.Id == testPlatformId))
//                {
//                    result = testPlatform;
//                    return result;
//                }
                return TestPlatforms.FirstOrDefault(testPlatform => testPlatform.Id == testPlatformId);
            }
            */
            
        }
        
        // 20141114
        // internal static ITestSuite GetTestSuite(string testSuiteName, string testSuiteId, string testPlatformId)
        internal static ITestSuite GetTestSuite(string testSuiteName, string testSuiteId, Guid testPlatformUniqueId)
        {
            ITestSuite result = null;
            
            if (!string.IsNullOrEmpty(testSuiteName)) {
                foreach (var testSuite in TestSuites.Where(ts => ts.Name == testSuiteName)) {
                    
                    // id does not match
                    if (!string.IsNullOrEmpty(testSuiteId) && testSuiteId != testSuite.Id)
                        continue;
                    // 20140902
//                    if (!string.IsNullOrEmpty(testSuiteId) && testSuiteId == testSuite.Id) {
//                        if (testPlatformId != testSuite.PlatformId)
//                            continue;
//                        result = testSuite;
//                    }
//                   
//                    if (string.IsNullOrEmpty(testSuiteId)) {
//                        // does this code ever work?
//                        if (testPlatformId != testSuite.PlatformId)
//                            continue;
//                        result = testSuite;
//                    }
//                    
//                    if (result != null)
//                        return result;
                    // 20140922
                    if (string.IsNullOrEmpty(testSuiteId) || testSuiteId == testSuite.Id)
                        // result = testSuite;
                        // 20141114
                        // if (testPlatformId == testSuite.PlatformId)
                        // 20141119
                        // if (testPlatformUniqueId == testSuite.PlatformId)
                        if (testPlatformUniqueId == testSuite.PlatformUniqueId)
                            result = testSuite;
                    if (null != result)
                       return result;
                }
            }
            
            if (!string.IsNullOrEmpty(testSuiteId)) {
                foreach (var testSuite in TestSuites) {
                    if (testSuite.Id == testSuiteId) {
                        
                        // 20141114
                        // if (testPlatformId != testSuite.PlatformId)
                        // 20141119
                        // if (testPlatformUniqueId != testSuite.PlatformId)
                        if (testPlatformUniqueId != testSuite.PlatformUniqueId)
                            continue;
                        if (testSuiteName != testSuite.Name && !string.IsNullOrEmpty(testSuiteName))
                            continue;
                        result = testSuite;
                        return result;
                    }
                }
            }
            return result;
        }
        
        internal static bool AddTestCase(
            string testCaseName,
            string testCaseId,
            string testCaseDescription,
            string testSuiteName,
            string testSuiteId,
            string testScenarioName,
            string testScenarioId,
            Guid testPlatformId,
            // 20141211
            // ScriptBlock[] testCode)
            ICodeBlock[] testCode)
        {
            bool result = false;
            
            var testSuite =
                GetTestSuite(
                    testSuiteName,
                    testSuiteId,
                    testPlatformId) ?? CurrentTestSuite;

            /*
            if (null == testSuite) { // ?? mistaken behavior ??
                
                testSuite = TestData.CurrentTestSuite;
            }
            */
            
            //var testScenario =
            //    GetTestScenario(
            //        testSuite,
            //        testScenarioName,
            //        testScenarioId,
            //        testSuiteName,
            //        testSuiteId,
            //        testPlatformId);
            
            //if (null == testScenario) { // ?? mistaken behavior ??
                
            //    testScenario = CurrentTestScenario;
            //}
            var testScenario =
                GetTestScenario(
                    testSuite,
                    testScenarioName,
                    testScenarioId,
                    testSuiteName,
                    testSuiteId,
                    testPlatformId) ?? CurrentTestScenario;

            //var testCase =
            //    new TestCase(
            //        testCaseName,
            //        testCaseId);

            //testCase.Description = testCaseDescription;
            //testCase.TestCode = testCode;
            var testCase =
                new TestCase(
                    testCaseName,
                    testCaseId)
                {
                    Description = testCaseDescription,
                    TestCode = testCode
                };

            CurrentTestCase = testCase;
            
            try {
                
                testScenario.TestCases.Add(testCase);
                result = true;
            }
            catch (Exception eFailedToAdd) {
                throw eFailedToAdd;
                //result = false;
            }
            
            return result;
        }
        
        internal static bool AddTestScenario(ITestSuite testSuite,
                                             string testScenarioName,
                                             string testScenarioId,
                                             string testScenarioDescription,
                                             string testSuiteName,
                                             string testSuiteId,
                                             Guid testPlatformId,
                                             // 20141211
                                             // ScriptBlock[] testScenarioBeforeTest,
                                             // ScriptBlock[] testScenarioAfterTest)
                                             ICodeBlock[] testScenarioBeforeTest,
                                             ICodeBlock[] testScenarioAfterTest)
        {
            bool result = false;
            
            // clean up the last empty test result
            // in the previous scenario
            if (null != CurrentTestScenario) {
                
                if (CurrentTestScenario.TestResults.Count > 0) {
                    
                    if (CurrentTestScenario.TestResults[CurrentTestScenario.TestResults.Count - 1].Details.Count == 0 &&
                        CurrentTestScenario.TestResults[CurrentTestScenario.TestResults.Count - 1].Status == TestStateNotTested) {

                        CurrentTestScenario.TestResults.RemoveAt(CurrentTestScenario.TestResults.Count - 1);
                    }
                }
                
//                if ((null != TestData.CurrentTestResult.Name &&
//                     string.Empty != TestData.CurrentTestResult.Name) ||
//                    (0 < TestData.CurrentTestResult.Details.Count)) {
//                    //TmxHelper.TestCaseStarted =
//                    //    System.DateTime.Now;
//                    TestData.CurrentTestScenario.TestResults.Add(new TestResult(TestData.CurrentTestScenario.Id, TestData.CurrentTestSuite.Id));
//                    TestData.CurrentTestScenario.TestResults[TestData.CurrentTestScenario.TestResults.Count - 1] =
//                        TestData.CurrentTestResult;
//                }
            }
            
            // set time spent on the previous scenario
            if (null != CurrentTestScenario) {
                
                if (DateTime.MinValue != CurrentTestScenario.Timestamp) {
                    
                    CurrentTestScenario.SetTimeSpent(
                        CurrentTestScenario.TimeSpent +=
                        (DateTime.Now - CurrentTestScenario.Timestamp).TotalSeconds);
                    CurrentTestScenario.Timestamp = DateTime.MinValue;
                }
            }
            
            if (testSuite != null) {
                
                CurrentTestSuite = testSuite;
            } else if (!string.IsNullOrEmpty(testSuiteName)) {
                
                var testSuite2 = GetTestSuite(testSuiteName, testSuiteId, testPlatformId);
                if (testSuite2 != null) {
                    
                    CurrentTestSuite = testSuite2;
                }
            } else if (!string.IsNullOrEmpty(testSuiteId)) {
                
                var testSuite3 = GetTestSuite(testSuiteName, testSuiteId, testPlatformId);
                if (testSuite3 != null) {
                    
                    CurrentTestSuite = testSuite3;
                }
            }
            
            if (CurrentTestSuite == null) {
                
                return result;
            }
            
            // 20140716
            try {
                // 20140716
                // if (1 == TestData.CurrentTestSuite.TestScenarios.Count && "autogenerated" == TestData.CurrentTestSuite.TestScenarios[0].Name &&
                // 20140718
                // if (1 == TestData.CurrentTestSuite.TestScenarios.Count && TestData.Autogenerated == TestData.CurrentTestSuite.TestScenarios[0].Name &&
                //     1 == TestData.CurrentTestSuite.TestScenarios[0].TestResults.Count && TestResultOrigins.Automatic == TestData.CurrentTestSuite.TestScenarios[0].TestResults[0].Origin) {
                if (1 <= CurrentTestSuite.TestScenarios.Count && Autogenerated == CurrentTestSuite.TestScenarios[0].Name &&
                    (0 == CurrentTestSuite.TestScenarios[0].TestResults.Count ||
                     1 == CurrentTestSuite.TestScenarios[0].TestResults.Count && TestResultOrigins.Automatic == CurrentTestSuite.TestScenarios[0].TestResults[0].Origin)) {
                    
                    CurrentTestSuite.TestScenarios.RemoveAt(0);
                }
            }
            catch {}
            
            if (string.IsNullOrEmpty(testScenarioId))
                testScenarioId = GetTestScenarioId();
            
//            if (null != TestData.TestSuites && 0 < TestData.TestSuites.Count) {
//                int lastTestSuiteNumber = TestData.TestSuites.Count - 1;
//
//                if (null != TestData.TestSuites[lastTestSuiteNumber].TestScenarios && 0 < TestData.TestSuites[lastTestSuiteNumber].TestScenarios.Count) {
//                    int lastTestScenarioNumber = TestData.TestSuites[lastTestSuiteNumber].TestScenarios.Count - 1;
//
//                    if (TestData.CurrentTestScenario.Name == TestData.TestSuites[lastTestSuiteNumber].TestScenarios[lastTestScenarioNumber].Name &&
//                        TestData.CurrentTestScenario.Id == TestData.TestSuites[lastTestSuiteNumber].TestScenarios[lastTestScenarioNumber].Id) {
//                        
//                        TestData.TestSuites[lastTestSuiteNumber].TestScenarios[lastTestScenarioNumber] = TestData.CurrentTestScenario;
//                    }
//                }
//            }
            
            CurrentTestSuite.TestScenarios.Add(
                new TestScenario(testScenarioName, testScenarioId, CurrentTestSuite.Id) { SuiteUniqueId = CurrentTestSuite.UniqueId });
            
            if (!string.IsNullOrEmpty(testScenarioDescription))
                CurrentTestSuite.TestScenarios[CurrentTestSuite.TestScenarios.Count - 1].Description = testScenarioDescription;
            
            CurrentTestScenario = 
                (TestScenario)CurrentTestSuite.TestScenarios[CurrentTestSuite.TestScenarios.Count - 1];
            
            CurrentTestScenario.BeforeTest = testScenarioBeforeTest;
            CurrentTestScenario.AfterTest = testScenarioAfterTest;
            
            CurrentTestScenario.PlatformUniqueId = testPlatformId != Guid.Empty ? testPlatformId : CurrentTestSuite.PlatformUniqueId;
            CurrentTestScenario.PlatformId = TestPlatforms.First(tp => tp.UniqueId == CurrentTestScenario.PlatformUniqueId).Id;
            
            // set the initial time for this scenario's session
            CurrentTestScenario.SetNow();
            
            OnTmxNewTestScenarioAdded(CurrentTestScenario, null);
            
            if (Preferences.Storage) {
                
                using (var session = StorageHelper.SessionFactory.OpenSession())
                    session.Save(CurrentTestScenario);
            }
            
            result = true;
            
            return result;
        }
        
        internal static ITestCase GetTestCase(
            ITestSuite testSuite,
            string testCaseName,
            string testCaseId,
            string testScenarioName,
            string testScenarioId,
            string testSuiteName,
            string testSuiteId,
            Guid testPlatformId)
        {
            ITestCase result = null;
            
            if (null == testSuite) {
                
                testSuite =
                    GetTestSuite(
                        testSuiteName,
                        testSuiteId,
                        testPlatformId);
                
            }
            
            if (null == testSuite)
                // better error description?
                return result;
            
            ITestScenario testScenario = null;
            
            if (null != testSuite)
                testScenario =
                    GetTestScenario(
                    testSuite,
                    testScenarioName,
                    testScenarioId,
                    testSuiteName,
                    testSuiteId,
                    testPlatformId);
            
            if (null == testScenario)
                // better error description?
                return result;
            
            if (null != testScenario && 0 < testScenario.TestCases.Count)
                foreach (var testCase in testScenario.TestCases)
                    if ((testCaseName == testCase.TestCaseName &&
                        testCaseId == testCase.TestCaseId) ||
                        (string.IsNullOrEmpty(testCaseName) && testCaseId == testCase.TestCaseId) ||
                        (string.IsNullOrEmpty(testCaseId) && testCaseName == testCase.TestCaseName)) {
                        
                        result = testCase;
                        break;
                    }
            
            return result;
        }
        
        internal static ITestScenario GetTestScenario(
            ITestSuite testSuite,
            string testScenarioName,
            string testScenarioId,
            string testSuiteName,
            string testSuiteId,
            Guid testPlatformId)
        {
            TestScenario result = null;
            if (testSuite != null)
                CurrentTestSuite = testSuite;
            else if (!string.IsNullOrEmpty(testSuiteName)) {
                /*
            } else if (testSuite == null && 
                        testSuiteName != string.Empty &&
                        testSuiteName != null) {
            */
                var testSuite2 = GetTestSuite(testSuiteName, testSuiteId, testPlatformId);
                if (testSuite2 != null)
                    CurrentTestSuite = testSuite2;
                
            } else if (!string.IsNullOrEmpty(testSuiteId)) {
                /*
            } else if (testSuite == null && 
                        testSuiteId != string.Empty &&
                        testSuiteId != null) {
            */
                var testSuite3 = GetTestSuite(testSuiteName, testSuiteId, testPlatformId);
                if (testSuite3 != null)
                    CurrentTestSuite = testSuite3;
            }
            
            if (CurrentTestSuite == null)
                return result;
            
            if (!string.IsNullOrEmpty(testScenarioName)) {
                
                foreach (ITestScenario testScenario in CurrentTestSuite.TestScenarios)
                    if (testScenario.Name == testScenarioName) {
                        
                        CurrentTestScenario = testScenario;
                        return CurrentTestScenario;
                        // TODO: try this
                        // return TestData.CurrentTestScenario = testScenario;
                    }
            }
            
            if (!string.IsNullOrEmpty(testScenarioId)) {
                // foreach (ITestScenario testScenario in TestData.CurrentTestSuite.TestScenarios.Cast<ITestScenario>().Where(testScenario => testScenario.Id == testScenarioId)) {
                foreach (ITestScenario testScenario in CurrentTestSuite.TestScenarios.Where(testScenario => testScenario.Id == testScenarioId)) {
                    if (testPlatformId != testScenario.PlatformUniqueId)
                        continue;
                    if (testScenarioName != testScenario.Name && !string.IsNullOrEmpty(testScenarioName))
                        continue;
                    CurrentTestScenario = testScenario;
                    return testScenario;
                }
            }

            return result;
        }
        
        internal static IOrderedEnumerable<ITestSuite> SearchTestSuite(
            Func<ITestSuite, bool> query,
            Func<ITestSuite, object> ordering,
            bool desc)
        {
            IOrderedEnumerable<ITestSuite> result = null;
            
            if (desc) {
                result =
                    from suite in TestSuites
                    where query(suite)
                    orderby ordering(suite) descending
                    select suite;
            } else {
                result =
                    from suite in TestSuites
                    where query(suite)
                    orderby ordering(suite) ascending
                    select suite;
            }
            return result;
        }
        
        static IEnumerable<ITestScenario> getAllScenarios()
        {
            return TestSuites.SelectMany(suite => suite.TestScenarios).ToList();
        }
        
        internal static IOrderedEnumerable<ITestScenario> SearchTestScenario(
            Func<ITestScenario, bool> query,
            Func<ITestScenario, object> ordering,
            bool desc)
        {
            IOrderedEnumerable<ITestScenario> result = null;
            
            if (desc) {
                result =
                    from scenario in getAllScenarios()
                    where query(scenario)
                    orderby ordering(scenario) descending
                    select scenario;
            } else {
                result =
                    from scenario in getAllScenarios()
                    where query(scenario)
                    orderby ordering(scenario) ascending
                    select scenario;
            }
            
            return result;
        }
        
        static IEnumerable<ITestResult> getAllTestResults()
        {
            return (from suite in TestSuites from ITestScenario scenario in suite.TestScenarios from ITestResult testResult in scenario.TestResults select testResult).ToList();
            /*
            List<TestResult> result = new List<TestResult>();
            foreach (TestSuite suite in TestData.TestSuites)
            {
                foreach (TestScenario scenario in suite.TestScenarios)
                {
                    foreach (TestResult testResult in scenario.TestResults)
                    {
                        result.Add(testResult);
                    }
                }
            }
            return result;
            */
        }
        
        internal static IOrderedEnumerable<ITestResult> SearchTestResult(
            Func<ITestResult, bool> query,
            Func<ITestResult, object> ordering,
            bool desc)
        {
            IOrderedEnumerable<ITestResult> result = null;
            
            if (desc) {
                result =
                    from testResult in getAllTestResults()
                    where query(testResult)
                    orderby ordering(testResult) descending
                    select testResult;
            } else {
                result =
                    from testResult in getAllTestResults()
                    where query(testResult)
                    orderby ordering(testResult) ascending
                    select testResult;
            }
            return result;
        }
    }
}
