//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tmx.Server.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogicConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogicConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tmx.Server.Logic.LogicConstants", typeof(LogicConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        public static string WorkflowLoader_BackSlashe {
            get {
                return ResourceManager.GetString("WorkflowLoader_BackSlashe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to htm.
        /// </summary>
        public static string WorkflowLoader_FileExtension_Htm {
            get {
                return ResourceManager.GetString("WorkflowLoader_FileExtension_Htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html.
        /// </summary>
        public static string WorkflowLoader_FileExtension_Html {
            get {
                return ResourceManager.GetString("WorkflowLoader_FileExtension_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        public static string WorkflowLoader_FileExtension_Xml {
            get {
                return ResourceManager.GetString("WorkflowLoader_FileExtension_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Workflows.
        /// </summary>
        public static string WorkflowLoader_FileSystemPath_Workflows {
            get {
                return ResourceManager.GetString("WorkflowLoader_FileSystemPath_Workflows", resourceCulture);
            }
        }
    }
}
