//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tmx.Server.Library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServerLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tmx.Server.Library.ServerLibrary", typeof(ServerLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new test client.
        /// </summary>
        internal static string ReasonPhrase_TestClientsModule_FailedToCreateNewTestClient {
            get {
                return ResourceManager.GetString("ReasonPhrase_TestClientsModule_FailedToCreateNewTestClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a test run.
        /// </summary>
        internal static string ReasonPhrase_TestRunsModule_FailedToCreateTestRun {
            get {
                return ResourceManager.GetString("ReasonPhrase_TestRunsModule_FailedToCreateTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find test run with id {0}.
        /// </summary>
        internal static string ReasonPhrase_TestRunsModule_FailedToFindTestRunWithId {
            get {
                return ResourceManager.GetString("ReasonPhrase_TestRunsModule_FailedToFindTestRunWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no test runs.
        /// </summary>
        internal static string ReasonPhrase_TestRunsModule_ThereAreNoTestRuns {
            get {
                return ResourceManager.GetString("ReasonPhrase_TestRunsModule_ThereAreNoTestRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s not been supplied the default parameter.
        /// </summary>
        internal static string ReasonPhrase_TestRunsModule_ThereHasNotBeenSuppliedTheDefaultParameter {
            get {
                return ResourceManager.GetString("ReasonPhrase_TestRunsModule_ThereHasNotBeenSuppliedTheDefaultParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no default workflow.
        /// </summary>
        internal static string ReasonPhrase_TestRunsModule_ThereIsNoDefaultWorkflow {
            get {
                return ResourceManager.GetString("ReasonPhrase_TestRunsModule_ThereIsNoDefaultWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no test client with id = {0}.
        /// </summary>
        internal static string ReasonPhrase_ThereIsNOTestClientWithId {
            get {
                return ResourceManager.GetString("ReasonPhrase_ThereIsNOTestClientWithId", resourceCulture);
            }
        }
    }
}
